default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # sslmode: require
  port: 5432

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: movie_explorer_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>