default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: movie_explorer_app

test:
  <<: *default
  database: movie_explorer_app_test

production:
  <<: *default
  url: <%= ENV['PRODUCTION_DATABASE_URL'] %>
  pool: 15
  sslmode: require